// AMS - This program was generated by cpp19|pg19.exe

// don't display warning at dbghelp.h lines 1544, and 3190 (c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h):
#pragma warning(disable : 4091)

#include <windows.h>
#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <thread>
#include <future>
#include <deque>
#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <sstream>
#include <algorithm>
#include <iterator>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <locale>
#include <functional>
// basic exception handler class:
struct QException : public std::exception
{
    QException(std::string msg) : std::exception(msg.c_str()) {}
    QException(char *msg) : std::exception(msg) {}
    virtual ~QException() {}
};
